version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/home/app
      - /home/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.example
    depends_on:
      - db
      - redis
    networks:
      - app_network
    command: >
      sh -c "npm run start"
  db:
    image: nicholasliem/wbd-m2-db-image:latest
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:latest
    networks:
      - app_network

networks:
  app_network:
    driver: bridge