version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - db
      - redis
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app
    command: [ "npm", "run", "dev" ]
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkin
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  redis:
    image: redis:latest
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
