version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db-data: