FROM node:20-alpine

RUN apk add --no-cache curl openssl
RUN mkdir -p /home/app/node_modules && chown -R node:node /home/app

WORKDIR /home/app

USER node

COPY --chown=node:node package*.json ./

RUN npm ci

COPY --chown=node:node . .

RUN npx prisma generate

ENV PORT=3000

EXPOSE 3000

CMD ["npm", "run", "start"]