-- Table structure for table "user"
CREATE TABLE "users" (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(255) NOT NULL UNIQUE,
  email varchar(255) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  full_name varchar(255),
  work_history TEXT,
  skills TEXT,
  profile_photo_path varchar(255) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL,
  PRIMARY KEY (id)
);

-- Table structure for table "feed"
CREATE TABLE "feed" (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL,
  content text NOT NULL,
  user_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT feed_user_id_fk_user_id FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE
);

-- Table structure for table "chat"
CREATE TABLE "chat" (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  timestamp timestamptz NOT NULL DEFAULT NOW(),
  from_id bigint NOT NULL,
  to_id bigint NOT NULL,
  message text NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT chat_from_id_fk_user_id FOREIGN KEY (from_id) REFERENCES "users" (id) ON DELETE CASCADE,
  CONSTRAINT chat_to_id_fk_user_id FOREIGN KEY (to_id) REFERENCES "users" (id) ON DELETE CASCADE
);

-- 
-- Table structure for table connection_request 
--

CREATE TABLE "connection_request" (
    from_id bigint NOT NULL,
    to_id bigint NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (from_id, to_id),
    CONSTRAINT connection_request_from_id_fk_user_id FOREIGN KEY (from_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT connection_request_to_id_fk_user_id FOREIGN KEY (to_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 
-- Table structure for table connection 
--

CREATE TABLE "connection" (
    from_id bigint NOT NULL,
    to_id bigint NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (from_id, to_id),
    CONSTRAINT connection_from_id_fk_user_id FOREIGN KEY (from_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT connection_to_id_fk_user_id FOREIGN KEY (to_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Table structure for table push_subscriptions
--
CREATE TABLE "push_subscriptions" (
  endpoint TEXT NOT NULL PRIMARY KEY,
  user_id bigint NULL,
  keys JSON NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT push_subscriptions_user_id_fk FOREIGN KEY (user_id) 
    REFERENCES users (id) ON DELETE SET NULL
);